---
- hosts: galaxyservers
  become: true
  vars:
    GALAXY_VERSION: release_23.0
    GALAXY_ADMIN_USERNAME: 'admin'
    GALAXY_ADMIN_PASSWORD: '123456'
    GALAXY_ADMIN_API_KEY: 'admin_key'
    GALAXY_ADMIN_EMAIL: 'admingalaxy@server.com'
  roles:
    - ansible-role-laniakea-galaxy
