---

- name: '[Ubuntu] Prevent nginx update from Ubuntu repository'
  copy:
    src: 'galaxyproject-nginx-pin-700'
    dest: '/etc/apt/preferences.d/'
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
- name: Include postgresql role
  include_role:
    name: galaxyproject.postgresql
- name: Include natefoo role
  include_role:
    name: natefoo.postgresql_objects
    apply:
      become: true
      become_user: postgres
  vars:
    postgresql_objects_users: "{{ galaxy_postgresql_objects_users }}"
    postgresql_objects_databases: "{{ galaxy_postgresql_objects_databases }}" 
- name: Include geerlingguy role
  include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
- name: Include galaxy role
  include_role:
    name: galaxyproject.galaxy
  vars:
    pip_virtualenv_command: /usr/bin/python3 -m virtualenv
    galaxy_create_user: true
    galaxy_force_checkout: true
    galaxy_separate_privileges: true
    galaxy_manage_paths: true
    galaxy_layout: root-dir
    galaxy_user: {name: galaxy, shell: /bin/bash}
    galaxy_root: /home/galaxy
    galaxy_commit_id: release_20.01
    galaxy_config_style: yaml
    galaxy_config_file: /home/galaxy/config/galaxy.yml
    galaxy_config:
      galaxy:
        brand: "My Galaxy"
        admin_users: "{{ GALAXY_ADMIN_EMAIL }}"
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
        install_database_connection: "postgresql:///galaxy_tools?host=/var/run/postgresql"
        file_path: /export/galaxy/database/files
        new_file_path: /export/galaxy/database/tmp
        check_migrate_tools: false
        tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
        nginx_upload_store: /export/galaxy/database/tmp/nginx_upload_store
        nginx_upload_path: "/_upload"
        require_login: "True"
        allow_user_creation: "True"
        allow_user_impersonation: "True"
        new_user_dataset_access_role_default_private: "True"
      uwsgi: 
        socket: 127.0.0.1:4001
        buffer-size: 16384
        processes: 3
        threads: 4
        offload-threads: 2
        static-map:
          - /static/style={{ galaxy_server_dir }}/static/style/blue
          - /static={{ galaxy_server_dir }}/static
          - /favicon.ico={{ galaxy_server_dir }}/static/favicon.ico
        static-safe: client/galaxy/images
        master: true
        virtualenv: "{{ galaxy_venv_dir }}"
        pythonpath: "{{ galaxy_server_dir }}/lib"
        module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
        #mount: /galaxy=galaxy.webapps.galaxy.buildapp:uwsgi_app()
        manage-script-name: true
        thunder-lock: true
        die-on-term: true
        hook-master-start:
          - unix_signal:2 gracefully_kill_them_all
          - unix_signal:15 gracefully_kill_them_all
        py-call-osafterfork: true
        enable-threads: true
        stats: 127.0.0.1:9191
        logto: /tmp/uwsgi.log
        no-orphans: true
- name: Include miniconda role
  include_role:
    name: uchida.miniconda
  vars:
    miniconda_prefix: "{{ galaxy_tool_dependency_dir }}/_conda"
    miniconda_version: "4.6.14"
- name: Include systemd role
  include_role:
    name: usegalaxy_eu.galaxy_systemd
  vars:
    galaxy_systemd_mode: mule
    galaxy_zergpool_listen_addr: 127.0.0.1:8080
- name: Install nginx dependencies
  apt:
    pkg: nginx-common=1.10.3-0ubuntu0.16.04.2ppa1
- name: Create tmp dir
  file:
    path: /export/galaxy/database/tmp
    state: directory
    owner: galaxy
    group: galaxy
- name: Create nginx_upload_store dir
  file:
    path: /export/galaxy/database/tmp/nginx_upload_store
    state: directory
    owner: www-data
    group: galaxy
- name: Include nginx role
  include_role:
    name: galaxyproject.nginx
  vars:
    nginx_selinux_allow_local_connections: true
    nginx_flavor: extras=1.10.3-0ubuntu0.16.04.2ppa1
    nginx_servers:
      - galaxy
    nginx_enable_default_server: false
    nginx_conf_http:
      client_max_body_size: 1g
- name: Change owner Galaxy dir
  file:
    path: /home/galaxy
    state: directory
    recurse: yes
    owner: galaxy
    group: galaxy
